"""
PDF report generation (reportlab).

Builds a one/two-page method-comparison report: logo, parameter, tolerance
settings, the plot, and the statistics — returned as PDF bytes for download.
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
)

ACCENT = colors.HexColor("#2563eb")
MUTED = colors.HexColor("#6b7280")
DARK = colors.HexColor("#1f2937")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("H", parent=ss["Title"], fontSize=18, textColor=DARK,
                          spaceAfter=2, alignment=0))
    ss.add(ParagraphStyle("Sub", parent=ss["Normal"], fontSize=10, textColor=MUTED,
                          spaceAfter=10))
    ss.add(ParagraphStyle("Sec", parent=ss["Heading2"], fontSize=12, textColor=ACCENT,
                          spaceBefore=10, spaceAfter=6))
    return ss


def _kv_table(rows, col_widths):
    t = Table(rows, colWidths=col_widths, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("TEXTCOLOR", (1, 0), (-1, -1), DARK),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, colors.HexColor("#e5e7eb")),
    ]))
    return t


def build_pdf(fig, stats, *, parameter, unit, tol, username, logo_path=None):
    """Return PDF bytes for the given figure + stats."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=16 * mm, bottomMargin=16 * mm,
                            title=f"Method Comparison Report — {parameter}")
    ss = _styles()
    story = []

    if logo_path:
        try:
            story.append(Image(logo_path, width=28 * mm, height=28 * mm))
            story.append(Spacer(1, 6))
        except Exception:
            pass

    story.append(Paragraph("Method Comparison Report", ss["H"]))
    unit_txt = f" ({unit})" if unit else ""
    story.append(Paragraph(
        f"Parameter: <b>{parameter}{unit_txt}</b> &nbsp;·&nbsp; "
        f"Generated by {username} on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        ss["Sub"]))

    # Tolerance settings
    story.append(Paragraph("Tolerance settings", ss["Sec"]))
    story.append(_kv_table([
        ["Threshold (X)", f"{tol['threshold']:g}"],
        ["Below threshold", f"{tol['val_below']:g} — {tol['type_below']}"],
        ["Above threshold", f"{tol['val_above']:g} — {tol['type_above']}"],
    ], [55 * mm, 100 * mm]))

    # Plot image
    story.append(Paragraph("Plot", ss["Sec"]))
    img_buf = io.BytesIO()
    fig.savefig(img_buf, format="png", dpi=200, bbox_inches="tight")
    img_buf.seek(0)
    story.append(Image(img_buf, width=170 * mm, height=95 * mm))
    story.append(Spacer(1, 6))

    # Statistics
    rng = (f"{stats['x_min']:.2f} – {stats['x_max']:.2f}"
           if _finite(stats["x_min"]) and _finite(stats["x_max"]) else "No valid range")
    story.append(Paragraph("Statistics", ss["Sec"]))
    story.append(_kv_table([
        ["Valid analysis range", rng],
        ["Mean-diff / OLS angle", f"{stats['ols_angle_deg']:.2f}°"],
        ["OLS slope", f"{stats['slope']:.4f}"],
        ["Mean difference", f"{stats['mean_diff']:.3f}"],
        ["Total points", str(stats["n_total"])],
        ["Points in valid range", str(stats["n_in_range"])],
    ], [55 * mm, 100 * mm]))

    ov, vr = stats["overall"], stats["valid_range"]
    story.append(Paragraph("Outlier breakdown", ss["Sec"]))
    header = ["", "Total", "Overestimated", "Underestimated"]
    data = [
        header,
        ["Overall",
         f"{ov['outliers_n']} ({ov['outliers_pct']:.1f}%)",
         f"{ov['over_n']} ({ov['over_pct']:.1f}%)",
         f"{ov['under_n']} ({ov['under_pct']:.1f}%)"],
        ["Valid range",
         f"{vr['outliers_n']} ({vr['outliers_pct']:.1f}%)",
         f"{vr['over_n']} ({vr['over_pct']:.1f}%)",
         f"{vr['under_n']} ({vr['under_pct']:.1f}%)"],
    ]
    t = Table(data, colWidths=[40 * mm, 40 * mm, 40 * mm, 40 * mm], hAlign="LEFT")
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("TEXTCOLOR", (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR", (0, 1), (0, -1), MUTED),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(t)

    doc.build(story)
    return buf.getvalue()


def _finite(v):
    try:
        return v == v and v not in (float("inf"), float("-inf"))
    except Exception:
        return False
